@echo off  
echo Starting debug server...  
node -e " >> start-debug.bat && echo const http = require('http'); >> start-debug.bat && echo const server = http.createServer((req, res) =^> { >> start-debug.bat && echo   console.log('Request:', req.method, req.url); >> start-debug.bat && echo   res.writeHead(200, {'Content-Type': 'application/json'}); >> start-debug.bat && echo   res.end(JSON.stringify({status: 'ok', dataMode: 'mock'})); >> start-debug.bat && echo }); >> start-debug.bat && echo server.listen(3001, '0.0.0.0', () =^> console.log('Server running on 0.0.0.0:3001')); >> start-debug.bat && echo "  
pause 
echo Starting server...  
